const PDFDocument = require('pdfkit');
const Expense = require('../models/expense.model');
const Income = require('../models/income.model');
const mongoose = require('mongoose');

exports.generateMonthlyReport = async (req, res) => {
  const { year, month } = req.query;

  const start = new Date(year, month - 1, 1);
  const end = new Date(year, month, 1);

  try {
    const income = await Income.aggregate([
      {
        $match: {
          user: new mongoose.Types.ObjectId(req.user.id),
          date: { $gte: start, $lt: end }
        }
      },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);

    const expense = await Expense.aggregate([
      {
        $match: {
          user: new mongoose.Types.ObjectId(req.user.id),
          date: { $gte: start, $lt: end }
        }
      },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);

    const totalIncome = income[0]?.total || 0;
    const totalExpense = expense[0]?.total || 0;
    const savings = totalIncome - totalExpense;
    const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
];


    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=monthly-report-${month}-${year}.pdf`
    );

    doc.pipe(res);

    doc.fontSize(22).text('Monthly Financial Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Month: ${months[month-1]}-${year}`);
    doc.moveDown();

    doc.fontSize(16).text(`Income: ₹ ${totalIncome.toLocaleString()}`);
    doc.text(`Expense: ₹ ${totalExpense.toLocaleString()}`);
    doc.text("-------------------------------------");
    doc.text(`Savings: ₹ ${savings.toLocaleString()}`);
    doc.text("-------------------------------------");

    doc.moveDown(2);
    doc.fontSize(12).text('Generated by ExpenseX');

    doc.end();
  } catch (err) {
    res.status(500).json({ message: 'Failed to generate PDF' });
  }
};


exports.generateYearlyReport = async (req, res) => {
  const year = Number(req.query.year);

  // Define full year range
  const start = new Date(year, 0, 1);   // Jan 1
  const end = new Date(year + 1, 0, 1); // Jan 1 next year

  try {
    const income = await Income.aggregate([
      {
        $match: {
          user: new mongoose.Types.ObjectId(req.user.id),
          date: { $gte: start, $lt: end }
        }
      },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);

    const expense = await Expense.aggregate([
      {
        $match: {
          user: new mongoose.Types.ObjectId(req.user.id),
          date: { $gte: start, $lt: end }
        }
      },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);

    const totalIncome = income[0]?.total || 0;
    const totalExpense = expense[0]?.total || 0;
    const savings = totalIncome - totalExpense;

    const doc = new PDFDocument();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=yearly-report-${year}.pdf`
    );

    doc.pipe(res);

    /* PDF CONTENT */
    doc.fontSize(22).text('Yearly Financial Report', { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).text(`Year: ${year}`);
    doc.moveDown();

    doc.fontSize(16).text(`Total Income: ₹ ${totalIncome.toLocaleString()}`);
    doc.text(`Total Expense: ₹ ${totalExpense.toLocaleString()}`);
    doc.text('----------------------------------------');
    doc.text(`Savings: ₹ ${savings.toLocaleString()}`);
    doc.text('----------------------------------------');

    doc.moveDown(2);
    doc.fontSize(12).text('Generated by ExpenseX');

    doc.end();
  } catch (err) {
    res.status(500).json({ message: 'Failed to generate yearly PDF' });
  }
};
